### PR TITLE
Upgrade Ruby, Rails and various gems

### PR DESCRIPTION
**Pull request by peter-hank**
https://cyber.harvard.edu/projectmanagement/issues/16955
https://cyber.harvard.edu/projectmanagement/issues/16956

### CODE REVIEW

**Comment by peter-hank** [comment]
Still on Rails `5.2.0` because of https://github.com/rzane/baby_squeel/issues/97.

**Comment by peter-hank** [comment]
@jdcc can you take a look?

I haven't tried to test any rake tasks, I'm not sure if any of them is still in use, if so, let me know.

**Comment by peter-hank** [comment]
We will need to reindex the search index.

**Comment by peter-hank** [comment]
@jdcc 

Yeah, my bad, incidently pushed the `5.2.3` Gemfile version. You can try again.

**Comment by peter-hank** [comment]
I've tested it with `PostgreSQL 12.0` and can't really see any issues. I've just exported the database from `9.3` and imported in `12`. Hopefully we don't need anything else.

**Comment by jdcc** [comment]
Looks good. I'll write up directions and have it deployed to QA.

**Pull request merged**
